const mongoose = require('mongoose');
const schemas = {
    blend: new mongoose.Schema({
        'Line': String,
        'Line Format': String,
        'Title': String,
        'Title Format': String,
        'Description': String,
        'Description Format': String,
        'Subtitle_1': String,
        'Subtitle_1 Format': String,
        '#Subtitle_1_Visible': String,
        '#Subtitle_1_Visible Format': String,
        'Subtitle_2': String,
        'Subtitle_2 Format': String,
        '#Subtitle_2_Visible': String,
        '#Subtitle_2_Visible Format': String,
        '@Image': String,
        '@Image Format': String,
        'Oils': String,
        'Oils Format': String,
    }),
    product: new mongoose.Schema({
        'Handle': String,
        'Handle Format': String,
        'Title': String,
        'Title Format': String,
        'Body (HTML)': String,
        'Body (HTML) Format': String,
        'Vendor': String,
        'Vendor Format': String,
        'Type': String,
        'Type Format': String,
        'Tags': String,
        'Tags Format': String,
        'Published': String,
        'Published Format': String,
        'Option1 Name': String,
        'Option1 Name Format': String,
        'Image Src': String,
        'Image Src Format': String,
        'Image Position': String,
        'Image Position Format': String,
        'Image Alt Text': String,
        'Image Alt Text Format': String
    }),
    variant: new mongoose.Schema({
        'Handle': String,
        'Handle Format': String,
        'Option1 Name': String,
        'Option1 Name Format': String,
        'Option1 Value': String,
        'Option1 Value Format': String,
        'Option2 Name': String,
        'Option2 Name Format': String,
        'Option2 Value': String,
        'Option2 Value Format': String,
        'Option3 Name': String,
        'Option3 Name Format': String,
        'Option3 Value': String,
        'Option3 Value Format': String,
        'Variant SKU': String,
        'Variant SKU Format': String,
        'Variant Grams': String,
        'Variant Grams Format': String,
        'Variant Inventory Tracker': String,
        'Variant Inventory Tracker Format': String,
        'Variant Inventory Qty': String,
        'Variant Inventory Qty Format': String,
        'Variant Inventory Policy': String,
        'Variant Inventory Policy Format': String,
        'Variant Fulfillment Service': String,
        'Variant Fulfillment Service Format': String,
        'Variant Price': String,
        'Variant Price Format': String,
        'Variant Compare At Price': String,
        'Variant Compare At Price Format': String,
        'Variant Requires Shipping': String,
        'Variant Requires Shipping Format': String,
        'Variant Taxable': String,
        'Variant Taxable Format': String,
        'Variant Barcode': String,
        'Variant Barcode Format': String,
        'Gift Card': String,
        'Gift Card Format': String,
        'SEO Title': String,
        'SEO Title Format': String,
        'SEO Description': String,
        'SEO Description Format': String,
        'Google Shopping / Google Product Category': String,
        'Google Shopping / Google Product Category Format': String,
        'Google Shopping / Gender': String,
        'Google Shopping / Gender Format': String,
        'Google Shopping / Age Group': String,
        'Google Shopping / Age Group Format': String,
        'Google Shopping / MPN': String,
        'Google Shopping / MPN Format': String,
        'Google Shopping / AdWords Grouping': String,
        'Google Shopping / AdWords Grouping Format': String,
        'Google Shopping / AdWords Labels': String,
        'Google Shopping / AdWords Labels Format': String,
        'Google Shopping / Condition': String,
        'Google Shopping / Condition Format': String,
        'Google Shopping / Custom Product': String,
        'Google Shopping / Custom Product Format': String,
        'Google Shopping / Custom Label 0': String,
        'Google Shopping / Custom Label 0 Format': String,
        'Google Shopping / Custom Label 1': String,
        'Google Shopping / Custom Label 1 Format': String,
        'Google Shopping / Custom Label 2': String,
        'Google Shopping / Custom Label 2 Format': String,
        'Google Shopping / Custom Label 3': String,
        'Google Shopping / Custom Label 3 Format': String,
        'Google Shopping / Custom Label 4': String,
        'Google Shopping / Custom Label 4 Format': String,
        'Variant Image': String,
        'Variant Image Format': String,
        'Variant Weight Unit': String,
        'Variant Weight Unit Format': String,
        'Variant Tax Code': String,
        'Variant Tax Code Format': String,
        'Cost per item': String,
        'Cost per item Format': String,
        'Status': String,
        'Status Format': String
    }),
    shopify: new mongoose.Schema({
        'Handle': String,
        'Handle Format': String,
        'Title': String,
        'Title Format': String,
        'Body (HTML)': String,
        'Body (HTML) Format': String,
        'Vendor': String,
        'Vendor Format': String,
        'Type': String,
        'Type Format': String,
        'Tags': String,
        'Tags Format': String,
        'Published': String,
        'Published Format': String,
        'Option1 Name': String,
        'Option1 Name Format': String,
        'Option1 Value': String,
        'Option1 Value Format': String,
        'Option2 Name': String,
        'Option2 Name Format': String,
        'Option2 Value': String,
        'Option2 Value Format': String,
        'Option3 Name': String,
        'Option3 Name Format': String,
        'Option3 Value': String,
        'Option3 Value Format': String,
        'Variant SKU': String,
        'Variant SKU Format': String,
        'Variant Grams': String,
        'Variant Grams Format': String,
        'Variant Inventory Tracker': String,
        'Variant Inventory Tracker Format': String,
        'Variant Inventory Qty': String,
        'Variant Inventory Qty Format': String,
        'Variant Inventory Policy': String,
        'Variant Inventory Policy Format': String,
        'Variant Fulfillment Service': String,
        'Variant Fulfillment Service Format': String,
        'Variant Price': String,
        'Variant Price Format': String,
        'Variant Compare At Price': String,
        'Variant Compare At Price Format': String,
        'Variant Requires Shipping': String,
        'Variant Requires Shipping Format': String,
        'Variant Taxable': String,
        'Variant Taxable Format': String,
        'Variant Barcode': String,
        'Variant Barcode Format': String,
        'Image Src': String,
        'Image Src Format': String,
        'Image Position': String,
        'Image Position Format': String,
        'Image Alt Text': String,
        'Image Alt Text Format': String,
        'Gift Card': String,
        'Gift Card Format': String,
        'SEO Title': String,
        'SEO Title Format': String,
        'SEO Description': String,
        'SEO Description Format': String,
        'Google Shopping / Google Product Category': String,
        'Google Shopping / Google Product Category Format': String,
        'Google Shopping / Gender': String,
        'Google Shopping / Gender Format': String,
        'Google Shopping / Age Group': String,
        'Google Shopping / Age Group Format': String,
        'Google Shopping / MPN': String,
        'Google Shopping / MPN Format': String,
        'Google Shopping / AdWords Grouping': String,
        'Google Shopping / AdWords Grouping Format': String,
        'Google Shopping / AdWords Labels': String,
        'Google Shopping / AdWords Labels Format': String,
        'Google Shopping / Condition': String,
        'Google Shopping / Condition Format': String,
        'Google Shopping / Custom Product': String,
        'Google Shopping / Custom Product Format': String,
        'Google Shopping / Custom Label 0': String,
        'Google Shopping / Custom Label 0 Format': String,
        'Google Shopping / Custom Label 1': String,
        'Google Shopping / Custom Label 1 Format': String,
        'Google Shopping / Custom Label 2': String,
        'Google Shopping / Custom Label 2 Format': String,
        'Google Shopping / Custom Label 3': String,
        'Google Shopping / Custom Label 3 Format': String,
        'Google Shopping / Custom Label 4': String,
        'Google Shopping / Custom Label 4 Format': String,
        'Variant Image': String,
        'Variant Image Format': String,
        'Variant Weight Unit': String,
        'Variant Weight Unit Format': String,
        'Variant Tax Code': String,
        'Variant Tax Code Format': String,
        'Cost per item': String,
        'Cost per item Format': String,
        'Status': String,
        'Status Format': String
    }),
    shopify_export: new mongoose.Schema({
        'Handle': String,
        'Title': String,
        'Body (HTML)': String,
        'Vendor': String,
        'Type': String,
        'Tags': String,
        'Published': String,
        'Option1 Name': String,
        'Option1 Value': String,
        'Option2 Name': String,
        'Option2 Value': String,
        'Option3 Name': String,
        'Option3 Value': String,
        'Variant SKU': String,
        'Variant Grams': String,
        'Variant Inventory Tracker': String,
        'Variant Inventory Qty': String,
        'Variant Inventory Policy': String,
        'Variant Fulfillment Service': String,
        'Variant Price': String,
        'Variant Compare At Price': String,
        'Variant Requires Shipping': String,
        'Variant Taxable': String,
        'Variant Barcode': String,
        'Image Src': String,
        'Image Position': String,
        'Image Alt Text': String,
        'Gift Card': String,
        'SEO Title': String,
        'SEO Description': String,
        'Google Shopping / Google Product Category': String,
        'Google Shopping / Gender': String,
        'Google Shopping / Age Group': String,
        'Google Shopping / MPN': String,
        'Google Shopping / AdWords Grouping': String,
        'Google Shopping / AdWords Labels': String,
        'Google Shopping / Condition': String,
        'Google Shopping / Custom Product': String,
        'Google Shopping / Custom Label 0': String,
        'Google Shopping / Custom Label 1': String,
        'Google Shopping / Custom Label 2': String,
        'Google Shopping / Custom Label 3': String,
        'Google Shopping / Custom Label 4': String,
        'Variant Image': String,
        'Variant Weight Unit': String,
        'Variant Tax Code': String,
        'Cost per item': String,
        'Status': String
    })
}
for(let schema of Object.values(schemas)) schema.index({'$**': 'text'});
module.exports = { 
	Blend:   { model: mongoose.model('Blend', schemas.blend), unique: ['Line', 'Title'] },
	Product: { model: mongoose.model('Product', schemas.product), unique: ['Handle'] },
	Variant: { model: mongoose.model('Variant', schemas.variant), unique: ['Handle', 'Option1 Value', 'Option2 Value', 'Option3 Value', 'Option4 Value'] },
    Shopify: { model: mongoose.model('Shopify', schemas.shopify), unique: ['Handle', 'Option1 Value', 'Option2 Value', 'Option3 Value', 'Option4 Value'] },
    Shopify_Export: { model: mongoose.model('Shopify_Export', schemas.shopify_export), unique: [] }
}