const mongoose = require('mongoose');
const schemas = {
	blend: new mongoose.Schema({
		'Line': String,
		'Title': String,
		'Description': String,
		'Subtitle_1': String,
		'#Subtitle_1_Visible': String,
		'Subtitle_2': String,
		'#Subtitle_2_Visible': String,
		'@Image': String,
		'Oils': String,
	}),
	product: new mongoose.Schema({
		'Handle': String,
		'Title': String,
		'Body (HTML)': String,
		'Vendor': String,
		'Type': String,
		'Tags': String,
		'Published': String,
		'Option1 Name': String,
		'Image Src': String,
		'Image Position': String,
		'Image Alt Text': String
	}),
	variant: new mongoose.Schema({
		'Handle': String,
		'Option1 Value': String,
		'Option2 Name': String,
		'Option2 Value': String,
		'Option3 Name': String,
		'Option3 Value': String,
		'Variant SKU': String,
		'Variant Grams': String,
		'Variant Inventory Tracker': String,
		'Variant Inventory Qty': String,
		'Variant Inventory Policy': String,
		'Variant Fulfillment Service': String,
		'Variant Price': String,
		'Variant Compare At Price': String,
		'Variant Requires Shipping': String,
		'Variant Taxable': String,
		'Variant Barcode': String,
		'Gift Card': String,
		'SEO Title': String,
		'SEO Description': String,
		'Google Shopping / Google Product Category': String,
		'Google Shopping / Gender': String,
		'Google Shopping / Age Group': String,
		'Google Shopping / MPN': String,
		'Google Shopping / AdWords Grouping': String,
		'Google Shopping / AdWords Labels': String,
		'Google Shopping / Condition': String,
		'Google Shopping / Custom Product': String,
		'Google Shopping / Custom Label 0': String,
		'Google Shopping / Custom Label 1': String,
		'Google Shopping / Custom Label 2': String,
		'Google Shopping / Custom Label 3': String,
		'Google Shopping / Custom Label 4': String,
		'Variant Image': String,
		'Variant Weight Unit': String,
		'Variant Tax Code': String,
		'Cost per item': String,
		'Status': String
	}),
	shopify: new mongoose.Schema({
		'Handle': String,
		'Title': String,
		'Body (HTML)': String,
		'Vendor': String,
		'Type': String,
		'Tags': String,
		'Published': String,
		'Option1 Name': String,
		'Option1 Value': String,
		'Option2 Name': String,
		'Option2 Value': String,
		'Option3 Name': String,
		'Option3 Value': String,
		'Variant SKU': String,
		'Variant Grams': String,
		'Variant Inventory Tracker': String,
		'Variant Inventory Qty': String,
		'Variant Inventory Policy': String,
		'Variant Fulfillment Service': String,
		'Variant Price': String,
		'Variant Compare At Price': String,
		'Variant Requires Shipping': String,
		'Variant Taxable': String,
		'Variant Barcode': String,
		'Image Src': String,
		'Image Position': String,
		'Image Alt Text': String,
		'Gift Card': String,
		'SEO Title': String,
		'SEO Description': String,
		'Google Shopping / Google Product Category': String,
		'Google Shopping / Gender': String,
		'Google Shopping / Age Group': String,
		'Google Shopping / MPN': String,
		'Google Shopping / AdWords Grouping': String,
		'Google Shopping / AdWords Labels': String,
		'Google Shopping / Condition': String,
		'Google Shopping / Custom Product': String,
		'Google Shopping / Custom Label 0': String,
		'Google Shopping / Custom Label 1': String,
		'Google Shopping / Custom Label 2': String,
		'Google Shopping / Custom Label 3': String,
		'Google Shopping / Custom Label 4': String,
		'Variant Image': String,
		'Variant Weight Unit': String,
		'Variant Tax Code': String,
		'Cost per item': String,
		'Status': String
	})
}
module.exports = { 
	Blend:   { model: mongoose.model('Blend', schemas.blend), unique: ['Line', 'Title'] },
	Product: { model: mongoose.model('Product', schemas.product), unique: ['Handle'] },
	Variant: { model: mongoose.model('Variant', schemas.variant), unique: ['Handle', 'Variant SKU'] },
	Shopify: { model: mongoose.model('Shopify', schemas.variant), unique: ['Handle', 'Variant SKU'] }
}